fails:TracePoint#raised_exception returns value from exception rescued on the :rescue event
